### PR TITLE
Add ingress to Helm chart

### PR DESCRIPTION
**Pull request by mtmn**

### CODE REVIEW

**Comment by mallow111** [comment]
@mtmn  can you rebase you changes, also can you put more description in the pr.

**Comment by mtmn** [comment]
@mallow111 definitely, totally forgot about this draft -- will continue working on this in the upcoming weeks.

**Comment by mallow111** [comment]
Great, will review it once it is up to date.

**Comment by hoerup** [comment]
Ingress is part of the current chart - so this can be closed

**Pull request closed without merging**
